export enum UserRole {
	ADMIN = "ADMIN",
	MANAGER = "MANAGER",
	EMPLOYEE = "EMPLOYEE",
	MAT_MANAGER = "MAT_MANAGER",
	DEP_MANAGER = "DEP_MANAGER",
	STOCK_MANAGER = "STOCK_MANAGER",
}

export enum CategoryType {
	PRODUCT = "PRODUCT",
	MATERIAL = "MATERIAL",
}

export enum ContactType {
	SUPPLIER = "SUPPLIER",
	CUSTOMER = "CUSTOMER",
}

export enum ContactStatus {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
}

export enum OrderStatus {
	ACCEPTED = "ACCEPTED",
	PROCESSING = "PROCESSING",
	SHIPPED = "SHIPPED",
	DELIVERED = "DELIVERED",
	CANCELLED = "CANCELLED",
}

export enum ReportAction {
	PRODUCT_RECEIVED = "PRODUCT_RECEIVED",
	PRODUCT_SHIPPED = "PRODUCT_SHIPPED",
	MATERIAL_RECEIVED = "MATERIAL_RECEIVED",
	MATERIAL_SHIPPED = "MATERIAL_SHIPPED",
	PRODUCT_PRODUCED = "PRODUCT_PRODUCED",
	MATERIAL_TRANSFERRED = "MATERIAL_TRANSFERRED",
	PRODUCT_TRANSFERRED = "PRODUCT_TRANSFERRED",
	ORDER_CREATED = "ORDER_CREATED",
	ORDER_UPDATED = "ORDER_UPDATED",
	INVENTORY_CHECK = "INVENTORY_CHECK",
	USER_REGISTERED = "USER_REGISTERED",
	USER_LOGGED_IN = "USER_LOGGED_IN",
	USER_LOGGED_OUT = "USER_LOGGED_OUT",
}